- hosts: all
  tasks:
    - name: Add_repository
      yum_repository:
        name: docker
        description: Docker repo
        baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
        gpgcheck: no
    
    - name: Installing Docker Software
      package:
        name: "docker-ce-18.06.3.ce-3.el7.x86_64"
        state: present
    
    - name: Start the Docker service
      service:
        name: "docker"
        state: started
    
    - pip:
        name: docker
    
    - name: Pull the httpd docker image from Dockerhub
      docker_image:
        name: "httpd"
        source: pull
    
    - name: Copy html page "task1.html"
      copy:
        src: "task1.html"
        dest: "/home"
    
    - name: Creating the Container with httpd image
      docker_container:
        name: webos
        image: httpd
        state: started
        ports:
          - "3000:80"
        volumes:
          -  /home:/usr/local/apache2/htdocs/
