- name: webserver on aws ec2 instance
  hosts: all
  vars_files:
          - key.yml 
  tasks:
          - name: VPC Subnet info
            ec2_vpc_subnet_info:
                    region: ap-south-1
                    aws_secret_key: "{{ awssecret }}"
                    aws_access_key: "{{ awsaccess }}"
            register: vpc
          - debug:
                  var: vpc.subnets[0].subnet_id          

          - name: Security Group
            ec2_group:
                    name: "ansible_task2"
                    description: security group for ssh and http
                    region: ap-south-1
                    aws_secret_key: "{{ awssecret }}"
                    aws_access_key: "{{ awsaccess }}"
                    rules:
                            - proto: tcp
                              from_port: 80
                              to_port: 80
                              cidr_ip: 0.0.0.0/0
                            - proto: tcp
                              from_port: 22
                              to_port: 22
                              cidr_ip: 0.0.0.0/0
            register: security_group
            
          - name: creating key pair
            ec2_key:
                    name: ansible_task2
                    region: ap-south-1
                    aws_secret_key: "{{ awssecret }}"
                    aws_access_key: "{{ awsaccess }}"
            register: key_pair

          - name: saving key
            copy:
                    content: "{{ key_pair.key }}"
                    dest: "ansible_task2"
                    mode: "0600"
            
          - name: Launching ec2 instance
            ec2:
                    assign_public_ip: yes
                    aws_access_key: "{{ awsaccess }}"
                    aws_secret_key: "{{ awssecret }}"
                    count: 1
                    group_id: "{{ security_group.group_id }}"
                    image: ami-0ebc1ac48dfd14136
                    instance_tags:
                            webos: httpd
                    instance_type: t2.micro
                    vpc_subnet_id: "{{ vpc.subnets[0].subnet_id }}"
                    wait: yes
                    key_name: "{{ key_pair.key.name }}"
                    region: ap-south-1
                    state: present
                    user_data: | 
                               #!/bin/bash
                               sudo yum install httpd php -y
                               sudo systemctl start httpd
                               sudo systemctl enable httpd
                               echo "Webserver configured using Ansible<br>Working Properly." >> /var/www/html/index.html
          - name: Gathering ec2 instance info
            ec2_instance_info:
                    region: ap-south-1
                    aws_access_key: "{{ awsaccess }}"
                    aws_secret_key: "{{ awssecret }}"
                    filters:
                            instance-state-name: running
            register: ec2instance
          - name: public url
            debug:
                    var: ec2instance.instances[0].network_interfaces[0].association.public_dns_name
